version: '3.8' 

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb_container 
    ports:
      - "27017:27017" 
    
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=dhh7824dwedhqhk378d23 
      
    depends_on:
      - mongo

    command: bash -c "npm update && npm i && npm run test"