name: continuos integrations

on:
  push:
    branches:
      - main
      - claudio 
  pull_request:
    branches:
      - main
      - claudio

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2

        with:
          node-version: 20.x

      - name: Install dependencies, build and test
        run: |
          npm install
          npm run build
          npm run test
