name: continuous integration

on:
  push:
    branches:
      - main
      - claudio 
  pull_request:
    branches:
      - main
      - claudio

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and run Docker Compose
        run: docker-compose up --build -d

      - name: Wait for Nest.js to be ready
        run: |
          while ! curl -s http://localhost:3000/health; do sleep 1; done

      - name: Run tests
        run: docker-compose exec app npm run test

      - name: Teardown
        if: always()
        run: docker-compose down